---
title: "in review"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
### **In Revision**
1. Summer Heat and Emergency Department Visits to US Children's Hospitals
2. Association between Hurricane Sandy and emergency department visits in New York City by age and cause
3. Habitual physical activity, fine particulate matter exposure, and the incidence risk of dementia
4. Long-term exposure to fine particulate matter and non-alcoholic fatty liver disease: A prospective cohort study
5. Global burden attributable to high sodium intake from 1990 to 2019


### **In Review** 
1. Heat alerts, mortality, and hospital admissions among older adults in the United States
2. Adverse pregnancy outcomes during the COVID-19 pandemic in the United States


### **In Review** 
1. Summer Heat and Emergency Department Visits to US Children's Hospitals
2. Association between Hurricane Sandy and emergency department visits in New York City by age and cause
3. Habitual physical activity, fine particulate matter exposure, and the incidence risk of dementia
4. Early life exposure to air pollution and cell-mediated immune responses in preschoolers.
5. Long-term exposure to fine particulate matter and non-alcoholic fatty liver disease: A prospective cohort study
6. HIV serostatus disclosure among men who have sex with men in China in the era of U=U and PrEP
7. Increase in diabetes deaths associated with COVID-19 pandemic in the United States
8. Covid-19 transmission dynamics among close contacts of Covid-19 index cases: a population-based cohort study in Zhejiang province, China
9. The Impact of Non-Acute Electronic Cigarette Use on Cardiovascular System: A Systematic Review and Meta-Analysis
10. Exploring the changing patterns of ischemic heart disease mortality during COVID-19 pandemic in the US
11. Global burden attributable to high sodium intake from 1990 to 2019
12. Demographics and epidemiology of global psoriasis prevalence: update from the GBD 2019 study

