---
pagetitle: "Publications - Shengzhi Sun"
---

```{=html}
<style type='text/css'>
body{ /* Normal  */
      margin-top: 22px;
      font-size: 16px;
      color: black
  }
#content .post-title {
 display: none;
}
</style>
```
\*Corresponding author

### **Selected Publications**
- Sun YT, Milando CW, Spangler KR, Wei YG, Schwartz J, Dominici F, Nori-Sarma A, **Sun SZ**\*, Wellenius GA. [Short-term exposure to low level ambient fine particulate matter and natural cause, cardiovascular and respiratory morbidity among US adults with health insurance: case time series study](lib/bmj-2023-076322.full.pdf). The BMJ 2024;384:e076322. http://dx.doi.org/10.1136/bmj-2023-076322

- Cao WN, Zhao S, **Sun SZ**\*. Editorial: [Mortality risks associated with floods: All cause, cardiovascular, and respiratory deaths rise in the weeks after an event](lib/bmj.p2101.full.pdf). The BMJ 2023;383:p2101. http://dx.doi.org/10.1136/bmj.p2101

-   **Sun SZ**\*, Weinberger KR, Nori-Sarma A, Spangler KR, Sun YT, Dominici F, Wellenius GA. [Ambient heat and risks of emergency department visits among adults in the United States: time-stratified case-crossover study](lib/bmj-2021-065653.full.pdf). The BMJ 2021;375:e065653. <https://doi.org/10.1136/BMJ-2021-065653> (First and corresponding author) (Editorial: Lang AE. [Role of energy in preventing heat related illness](lib/bmj.n3117.full.pdf). The BMJ 2021;375:n3117)
- Zhao S, Cao WN, Liao GZ, Guo ZH, Xu LF, Shen C, Chang C, Liang X, Wang K, He DH, **Sun SZ**\*, Chen R, Dominici F. [All cause and cause specific mortality associated with transition to daylight saving time in US: nationwide, time series, observational study](lib/e000771.full.pdf). BMJ Medicine 2024;3(1):e000771. http://dx.doi.org/10.1136/bmjmed-2023-000771
-   **Sun SZ**, Cao WN, Ge Y, Ran JJ, Sun F, Zeng Q, Guo MD, Huang JX, Lee RSY, Tian LW, Wellenius GA. [Outdoor light at night and risk of coronary heart disease among older adults: A prospective cohort study](lib/ehaa846.pdf). European Heart Journal 2021;42(8):822-830. <https://doi.org/10.1093/eurheartj/ehaa846> (First author) (Editorial: Munzel T, Hahad O, Daiber A. [The dark side of nocturnal light pollution: Outdoor light at night increases risk of coronary heart disease](lib/ehaa866.pdf). European Heart Journal 2021;42:831-834)
-   Nori-Sarma A, **Sun SZ**\*, Sun YT, Spangler KR, Oblath R, Galea S, Gradus JL, Wellenius GA. [Association between ambient heat and risk of emergency department visits for mental health among US, 2010-2019](lib/jamapsychiatry_norisarma_2022.pdf). JAMA Psychiatry 2022;79(4):341-349. <https://doi.org/10.1001/jamapsychiatry.2021.4369> (Corresponding author) (Editorial: Obradovich N, Ninor K. [Identifying and preparing for mental health burden of climate change](lib/jamapsychiatry_obradovich_2022_ed_210013_1645467162.82451.pdf). JAMA Psychiatry 2022). **Faculty Opinions Recommended** (ESI highly cited papers)
- Ran JJ, Zhao S, Han LF, Ge Y, Chong MKC, Cao WN, **Sun SZ**\*. [Increase in Diabetes Mortality Associated with COVID-19 Pandemic in the United States](lib/dc21-0213.full.pdf). Diabetes Care 2021; 44(7):e146-e147. <https://doi.org/10.2337/dc21-0213>
- **Sun SZ**, Yang QQ, Zhou QX, Cao WN, Yu SW, Zhan SY, Sun F. [Long-term exposure to fine particulate matter and non-alcoholic fatty liver disease: A prospective cohort study](lib/gutjnl-2021-324364.full.pdf). Gut 2022;71:443-445. <https://doi.org/10.1136/gutjnl-2021-324364>



### **First or Corresponding Author**
1. Liang T, Zhang YC, Cao WN, Li YF, Zeng Q, **Sun SZ**\*. Exposure to residential green space and semen quality among Chinese men. Ecotoxicology and Environmental Safety 2024; 
62. Liu RY, Li CR, Liang T, Zeng Q, **Sun SZ**, Zhao S, Cao WN. Within-week day and time of birth and risk of unexpected newborn complications in term singleton births: nationwide, population-based, observational study. 2024;
1. Lv X, Lin GY, Zhang YC, Yuan K, Liang T, Liu RY, Du Y, Yu HL,**Sun SZ**\*. [Weekly-specific ambient PM~1~ before and during pregnancy and the risk of gestational diabetes mellitus](lib/1-s2.0-S0147651324010820-main.pdf). Ecotoxicology and Environmental Safety 2024;284:117006. https://doi.org/10.1016/j.ecoenv.2024.117006
60. Han Z, Liu JY, Liang T, Yin J, Wei J, Zeng Q, Cao WN, Liu CJ, **Sun SZ**\*. [Exposure to ambient particulate matter and ovarian reserve impairment among reproductive age women in China](lib/1-s2.0-S0304389424027912-main.pdf). Journal of Hazardous Materials 2024;480: 136212. https://doi.org/10.1016/j.jhazmat.2024.136212
1. Yuan K, Lv X, Zhang YC, Liu RY, Liang T, Zhang ZY, Cao WN, Wu LZ, **Sun SZ**\*. [Exposure to hourly ambient temperature and temperature change between neighboring days and risk of emergency department visits for cause-specific cardiovascular disease](lib/1-s2.0-S2212095524003948-main.pdf). Urban Climate 2024;58:102197. https://doi.org/10.1016/j.uclim.2024.102197
1. Li CC, Meng XN, Zhang J, Wang HT, Lu HM, Cao ML,  **Sun SZ**\*, Wang YX. [Associations of metabolic changes and polygenic risk scores with cardiovascular outcomes and all-cuase mortality across BMI categories: a prospective cohort study](lib/s12933-024-02332-w.pdf). Cardiovascular Diabetology 2024;23:231. https://doi.org/10.1186/s12933-024-02332-w
1. Wang HT, Liu D, Meng XN, Sun WX, Li cc, Lu HM, Zheng DQ, Wu LJ, **Sun SZ**\*, Wang YX. [Immunoglobulin G N-Glycosylation and Senescence-Associated Secretory Phenotype](lib/ijms-25-06337.pdf). International Journal of Molecular Sciences 2024; 25: 6337. https://doi.org/10.3390/ijms25126337
1. Shi YD, Zhang YC, Yuan K, Han Z, Zhao S, Zhang ZY, Cao WN, Li YF, Zeng Q, **Sun SZ**\*. [Exposure to ambient ozone and sperm quality among adult men in China](lib/1-s2.0-S0147651324008297-main.pdf). Ecotoxicology and Environmental Safety 2024; 283: 116753. 	
https://doi.org/10.1016/j.ecoenv.2024.116753

1. Zhang YC, Zhao S, Cao WN, **Sun SZ**\*, Zeng Q, Luo P. [Ambient ozone exposure, semen plasma metabolites, and sperm quality decline among adult men in Wuhan China](lib/zhang-et-al-2024-ambient-ozone-exposure-semen.pdf). Environment & Health  2024;2(10): 729-738. https://doi.org/10.1021/envhealth.4c00066 
1. Wu HS, Liu JQ, Conway E, Zhan N, Chen ZS, **Sun SZ**\*, Li JH. [Fine particulate matter components and depression among middle-aged and older adults in China](lib/1-s2.0-S0048969724043766-main.pdf). Science of the Total Environment 2024;946:174228. https://doi.org/10.1016/j.scitotenv.2024.174228

1. Cao WN, Li CR, Sun F, Shi YH, Ji Y, Lin H, Ni MJ, **Sun SZ**\*, Chang C. Maternal sexually transmitted infections and congenital anomalies among newborns in the United States. 2024; 

1. Niu HX, Xu MJ, Tu PC, Xu YF, Li XQ, Xing ML, Chen ZJ, Wang XF, Lou XM, Wu LZ, **Sun SZ**\*. [Emerging contaminants: an emerging risk factor for diabetes mellitus](lib/toxics-12-00047.pdf). Toxics 2024; 12(1):47. https://doi.org/10.3390/toxics12010047
1. Yao XX, Tong XN, Shen C, Song YC, **Sun SZ**\*, Chen K, Shen HY. [Green space, genetic susceptibility, and risk of incident osteoporosis: a prospective cohort study from the UK Biobank](lib/1-s2.0-S0045653524005253-main.pdf). Chemosphere 2024;353:141632. 141632. https://doi.org/10.1016/j.chemosphere.2024.141632

1. Zhao S, Cao WN, Liao GZ, Guo ZH, Xu LF, Shen C, Chang C, Liang X, Wang K, He DH, **Sun SZ**\*, Chen R, Dominici F. [All cause and cause specific mortality associated with transition to daylight saving time in US: nationwide, time series, observational study](lib/e000771.full.pdf). BMJ Medicine 2024;3(1):e000771. http://dx.doi.org/10.1136/bmjmed-2023-000771
2. Zhang YC, Wei J, Zhao S, Zeng Q, **Sun SZ**\*, Cao WN. [Ambient fine particulate matter constituents and semen quality among adult men in China](lib/1-s2.0-S0304389423025979-main.pdf). Journal of Hazardous Materials 2024;465:133313. https://doi.org/10.1016/j.jhazmat.2023.133313
3. Yuan K, Zhang YC, Lv Xin, Cao WN, Zhang ZY, Wu LZ, **Sun SZ**\*. [Exposure to hourly ambient air pollutants and risk of emergency department visits for asthma: a multicenter time-stratified case-crossover analysis](lib/1-s2.0-S1352231023007331-main.pdf). Atmospheric Environment 2024;319:120307. https://doi.org/10.1016/j.atmosenv.2023.120307
1. Sun YT, Milando CW, Spangler KR, Wei YG, Schwartz J, Dominici F, Nori-Sarma A, **Sun SZ**\*, Wellenius GA. [Short-term exposure to low level ambient fine particulate matter and natural cause, cardiovascular and respiratory morbidity among US adults with health insurance: case time series study](lib/bmj-2023-076322.full.pdf). The BMJ 2024;384:e076322. http://dx.doi.org/10.1136/bmj-2023-076322

1. Cao WN, Zhao S, **Sun SZ**\*. Editorial: [Mortality risks associated with floods: All cause, cardiovascular, and respiratory deaths rise in the weeks after an event](lib/bmj.p2101.full.pdf). The BMJ 2023;383:p2101. http://dx.doi.org/10.1136/bmj.p2101
1. Zhang YC, Shi WY, Zhang M, Xu LF, Wu LZ, Li CR, Zhang ZY, Cao WN, Zhang J, Zeng Q, **Sun SZ**\*. [Exposure to PM~2.5~, seminal plasma metabolome, and semen quality among Chinese adult men: Association and potential mediation analyses](lib/1-s2.0-S030438942301885X-main.pdf). Journal of Hazardous Materials 2024; 461:132602. https://doi.org/10.1016/j.jhazmat.2023.132602 

1. Lv X, Shi WY, Yuan K, Zhang YC, Cao WN, Li CR, Xu LF, Wu LZ, **Sun SZ**\*, Hong F. [Hourly air pollution exposure and emergency hospital admissions for stroke: a multicenter case-crossover study](lib/lv-et-al-2023-hourly.pdf). Stroke 2023;54(12): 3038-3045; http://dx.doi.org/10.1161/STROKEAHA.123.044191
1. Li X, Wu HS, Xing WW, Xia WR, Jia PP, Yuan K, Guo F, Ran JJ, Wang XL, Ren YX, Dong LN, **Sun SZ**\*, Xu DG, Li JH. [Short-term association of fine particulate matter and its constituents with oxidative stress, symptoms and quality of life in patients with allergic rhinitis: A panel study](lib/1-s2.0-S0160412023005925-main.pdf). Environment International 2023;182:108319. https://doi.org/10.1016/j.envint.2023.108319
1. Zhang YC, Wei J, Liu C, Cao WN, Zhang ZY, Li YF, Zeng Q, **Sun SZ**\*. [Association between ambient PM~1~ and semen quality: A cross-sectional study of 27,854 men in China](lib/1-s2.0-S0160412023001927-main.pdf). Environment International 2023;175:107919. https://doi.org/10.1016/j.envint.2023.107919
1. Yuan K, Sun F, Zhang YC, Du Y, Wu LZ, Ge Y, Zhang ZY, Cao WN, **Sun SZ**\*. [Maternal exposure to ozone and risk of gestational hypertension and eclampsia in the United States](lib/1-s2.0-S0048969723009087-main.pdf). Science of the Total Environment 2023; 872:162292. https://doi.org/10.1016/j.scitotenv.2023.162292
2. Zhang YC, Sun F, Yuan K, Du Y, Wu LZ, Ge Y, Zhang ZY, **Sun SZ**\*, Cao WN. [Ambient temperature and major structural anomalies: A retrospective study of over 2 million newborns](lib/1-s2.0-S0048969723022325-main.pdf). Science of the Total Environment 2023; 882:163613. https://doi.org/10.1016/j.scitotenv.2023.163613
1. **Sun SZ**\*, Wang JJ, Cao WN, Wu LZ, Tian Y, Sun F, Zhang ZY, Ge Y, Du JQ, Li XB, Chen R. [A nationwide study of maternal exposure to ambient ozone and term birth weight in the United States](lib/1-s2.0-S0160412022004810-main.pdf). Environment International 2022; 170:107554. https://doi.org/10.1016/j.envint.2022.107554
1. **Sun SZ**\*, Wu J, Chen R, Levitt M. [SARS-CoV-2 Omicron variant: viral spread dynamics, disease burden, and vaccine effectiveness](lib/s44194-022-00014-x.pdf). Current Medicine 2022; 1(1):1-14. https://doi.org/10.1007/s44194-022-00014-x 
1. Cao WN, **Sun SZ**\*, Danilack VA. [Analysis of gestational weight gain during the COVID-19 pandemic in the US](lib/cao_2022_ld_220196_1661960683.57407.pdf). JAMA Network Open 2022; 5(9):e2230954. https://doi.org/10.1001/jamanetworkopen.2022.30954
1. **Sun SZ**\*, Cao WN, Ge Y, Siegel M, Wellenius GA. [Analysis of firearm violence during the COVID-19 pandemic in the United States](lib/sun_2022_oi_220283_1650462137.23246.pdf). JAMA Network Open 2022; 5(4):e229393. <https://doi.org/10.1001/jamanetworkopen.2022.9393>
2.  **Sun SZ**, Yang QQ, Zhou QX, Cao WN, Yu SW, Zhan SY, Sun F. [Long-term exposure to air pollution, habitual physical activity and risk of non-alcoholic fatty liver disease: A prospective cohort study](lib/1-s2.0-S0147651322002809-main.pdf). Ecotoxicology and Environmental Safety 2022; 235 (2022):113440. <https://doi.org/10.1016/j.ecoenv.2022.113440>
3.  Nori-Sarma A, **Sun SZ**\*, Sun YT, Spangler KR, Oblath R, Galea S, Gradus JL, Wellenius GA. [Association between ambient heat and risk of emergency department visits for mental health among US, 2010-2019](lib/jamapsychiatry_norisarma_2022.pdf). JAMA Psychiatry 2022; 79(4):341-349. <https://doi.org/10.1001/jamapsychiatry.2021.4369> (Editorial: Obradovich N, Ninor K. [Identifying and preparing for mental health burden of climate change](lib/jamapsychiatry_obradovich_2022_ed_210013_1645467162.82451.pdf). JAMA Psychiatry 2022) **Faculty Opinions Recommended** (ESI highly cited papers)
4.  Du JQ, Sun HF, Sun YY, Du JF, Cao WN, **Sun SZ**\*. [Assessment of age, period, and cohort effects of lung cancer incidence in Hong Kong and projection up to 2030 based on changing demographics](lib/ajcr0138826.pdf). American Journal of Cancer Research 2021; 11(12):5902-5916. <https://doi.org/10.1136/ajcr0138826>
5.  **Sun SZ**\*, Weinberger KR, Nori-Sarma A, Spangler KR, Sun YT, Dominici F, Wellenius GA. [Ambient heat and risks of emergency department visits among adults in the United States: time-stratified case-crossover study](lib/bmj-2021-065653.full.pdf). The BMJ 2021; 375:e065653. <https://doi.org/10.1136/BMJ-2021-065653> (Editorial: Lang AE. [Role of energy in preventing heat related illness](lib/bmj.n3117.full.pdf). BMJ 2021; 375:n3117)
6.  Wu XM, Du JQ, Li LC, Cao WN, **Sun SZ**\*. [Bayesian age-period-cohort prediction of mortality of type 2 diabetic kidney disease in China: A modeling study](lib/fendo-12-767263.pdf). Frontiers in Endocrinology 2021; 12:767263. <https://doi.org/10.3389/fendo.2021.767263>
7.  **Sun SZ**\*, Savitz DA, Wellenius GA. [Changes in adverse pregnancy outcomes associated with the COVID-19 pandemic in the United States](lib/sun_2021_ld_210217_1633537630.05761.pdf). JAMA Network Open 2021; 4(10):e2129560. <https://doi.org/10.1001/jamanetworkopen.2021.29560>
8.  Han LF, Zhao S, Cao WN, Javanbakht M, Ran JJ, **Sun SZ**\*. [Changes in renal failure mortality during the COVID-19 pandemic in the United States](lib/Han2021_Article_ChangesInRenalFailureMortality.pdf). Journal of Nephrology 2021; 34:2167-2170. <https://doi.org/10.1007/s40620-021-01145-4>
9.  Chen XB, Du JQ, Wu XM, Cao WN, **Sun SZ**\*. [Global burden attributable to high sodium intake from 1990 to 2019](lib/1-s2.0-S093947532100404X-main.pdf). Nutrition, Metabolism, and Cardiovascular Diseases 2021; 31: 3314-3321. <https://doi.org/10.1016/j.numecd.2021.08.033>
10. Xu QQ, Du JQ, Cao WN, **Sun SZ**\*. [Demographic and epidemiologic drivers of global burden of psoriasis](lib/ajd.13710.pdf). Australasian Journal of Dermatology 2021; 62:e554-e558. <https://doi.org/10.1111/ajd.13710>
11. Bernstein AS, **Sun SZ**\*, Weinberger KR, Spangler KR, Sheffield PE, Wellenius GA. [Warm Season and Emergency Department Visits to US Children's Hospitals](lib/EHP8083.pdf). Environmental Health Perspectives 2021;130(1): 017001. <https://doi.org/10.1289/EHP8083> (Editorial: Nicole W. [It's hot out there: Extreme temperatures and children's emergency department visits](lib/EHP10850.pdf). Environmental Health Perspectives 2022; 130(2):024003)
12. Ran JJ, Zhao S, Han LF, Ge Y, Chong MKC, Cao WN, **Sun SZ**\*. [Increase in Diabetes Mortality Associated with COVID-19 Pandemic in the United States](lib/dc21-0213.full.pdf). Diabetes Care 2021; 44(7):e146-e147. <https://doi.org/10.2337/dc21-0213>.
13. **Sun SZ**, Yang QQ, Zhou QX, Cao WN, Yu SW, Zhan SY, Sun F. [Long-term exposure to fine particulate matter and non-alcoholic fatty liver disease: A prospective cohort study](lib/gutjnl-2021-324364.full.pdf). Gut 2022;71:443-445. <https://doi.org/10.1136/gutjnl-2021-324364>
14. Wang LN, Du JQ, Cao WN, **Sun SZ**\*. [Trends of stroke attributable to high sodium intake at the global, regional, and national levels from 1990 to 2019: a population-based study](lib/NR.pdf). Neurological Research 2021; 43(6):474-481. <https://doi.org/10.1080/01616412.2020.1867950>
15. Ge Y, **Sun SZ** (**equal contributors**), Shen Y. [Estimation of case-fatality rate in COVID-19 patients with hypertension and diabetes melltius in the New York State: a preliminary report](lib/estimation-of-case-fatality-rate-in-covid-19-patients-with-hypertension-and-diabetes-mellitus-in-the-new-york-state-a-preliminary-report.pdf). Epidemiology & Infection 2021; 149:e14. <https://doi.org/10.1017/S0950268821000066>
16. **Sun SZ**, Cao WN, Ge Y, Ran JJ, Sun F, Zeng Q, Guo MD, Huang JX, Lee RSY, Tian LW, Wellenius GA. [Outdoor light at night and risk of coronary heart disease among older adults: A prospective cohort study](lib/ehaa846.pdf). European Heart Journal 2021; 42 (8):822-830. <https://doi.org/10.1093/eurheartj/ehaa846> (Editorial: Munzel T, Hahad O, Daiber A. [The dark side of nocturnal light pollution: Outdoor light at night increases risk of coronary heart disease](lib/ehaa866.pdf). European Heart Journal 2021; 42:831-834)
17. Du JQ, Wang LN, Wu XM, Cao WN, **Sun SZ**\*. [A comparative study of the disease burden attributable to PM~2.5~ in China, Japan and South Korea between 1990 and 2017](lib/1-s2.0-S0147651320316924-main.pdf). Ecotoxicology and Environmental Safety 2021; 209:11856. <https://doi.org/10.1016/j.ecoenv.2020.111856>
18. Wang LN, Wu XM, Du JQ, Cao WN, **Sun SZ**\*. [Global burden of ischemic heart disease attributable to ambient particulate matter pollution from 1990 to 2017](lib/1-s2.0-S0045653520323298-main.pdf). Chemosphere 2021; 263:128134. <https://doi.org/10.1016/j.chemosphere.2020.128134>
19. **Sun SZ**, Zhao JZ, Cao WN, Zheng TZ, Lu WQ, Zeng Q. [Identifying critical exposure windows for ambient air pollution and semen quality in Chinese men](lib/1-s2.0-S0013935120307891-main.pdf). Environmental research 2020; 189:109894. <https://doi.org/10.1016/j.envres.2020.109894>
20. **Sun SZ**\*, Weinberger KR, Yan ML, Anderson BG, Wellenius GA. [Tropical Cyclones and Risk of Preterm Birth: A Retrospective Analysis of 20 Million Births across 378 US Counties](lib/1-s2.0-S0160412020317803-main.pdf). Environment International 2020; 140:105825. <https://doi.org/10.1016/j.envint.2020.105825>
21. Yang G, **Sun SZ**\*. [Estimation of coronavirus disease case-fatality risk in real time](lib/EID.pdf). Emerging Infectious Diseases 2020;26 (8):1922-1923. <https://doi.org/10.3201/eid2608.201096>
22. **Sun SZ**, Cao WN, Chan KP, Ran JJ, Ge Y, Zhang YQ, Feng YL, Zeng Q, Lee RSY, Wong CM, Tian L, Lei YJ. [Cigarette smoking increases deaths associated with air pollution in Hong Kong](lib/1-s2.0-S135223102030008X-main.pdf). Atmospheric Environment 2020; 223:117266. <https://doi.org/10.1016/j.atmosenv.2020.117266>
23. Cao W, **Sun SZ** (**equal contributors**), Peng L, Gu J, Hao C, Li J, Wei D, Li J. [Low willingness to self-pay for pre-exposure prophylaxis (PrEP) among men who have sex with men (MSM) in China](lib/Cao-2020.pdf). BMC Public Health 2020; 20:337. <https://doi.org/10.1186/s12889-020-08488-w>
24. **Sun SZ**, Sarkar C, Kumari S, James P, Cao WN, Lee RSY, Tian LW, Webster C. [Air pollution associated respiratory mortality risk alleviated by residential greenness in the Chinese Elderly Health Service Cohort](lib/Sun-Air%20pollution%20associated%20respiratory%20morta.pdf). Environmental Research 2020; 183: 109139. <https://doi.org/10.1016/j.envres.2020.109139>
25. **Sun SZ**, Cao WN, Qiu H, Ran JJ, Lin HL, Shen C, Lee RSY, Tian L. [Benefits of physical activity not affected by air pollution: a prospective cohort study](lib/dyz184.pdf). International Journal of Epidemiology 2020;142-152. <https://doi.org/10.1093/ije/dyz184> (ESI highly cited papers)
26. **Sun SZ**\*, Stewart JD, Eliot MN, Yanosky JD, Liao DP, Tinker LF, Eaton CB, Whitsel EA, Wellenius GA. [Short-term exposure to air pollution and incidence of stroke in the Women's Health Initiative](lib/Sun-Short-term%20exposure%20to%20air%20pollution%20and%20i.pdf). Environment International 2019; 132:105065. <https://doi.org/10.1016/j.envint.2019.105065>
27. **Sun SZ**\*, Spangler KR, Weinberger KR, Yanosky JD, Braun JM, Wellenius GA. [Ambient temperature and markers of fetal growth: A retrospective observational study of 29 million singleton births](lib/EHP4648.pdf). Environmental Health Perspectives 2019; 127(6):067005. <https://doi.org/10.1289/EHP4648> (Editorial: Konkel L. [Hot temperatures during pregnancy: Evidence for an impact on fetal growth](lib/EHP6169.pdf). Environmental Health Perspectives 2020; 128(3):034002; [Chinese version](lib/EHP6169-ZH.pdf))
28. **Sun SZ**, Cao W, Pun VC, Qiu H, Ge Y, Tian L. [Respirable particulate constituents and risks of cause-specific mortality in the Hong Kong population](lib/acs.est.9b01635.pdf). Environmental Science & Technology 2019; 53(16):9810-9817. <https://doi.org/10.1021/acs.est.9b01635>
29. **Sun SZ**\*, Weinberger KR, Spangler KR, Eliot MN, Braun JM, Wellenius GA. [Ambient temperature and preterm birth: A retrospective study of 32 million US singleton births](lib/1-s2.0-S0160412018324486-main.pdf). Environment International 2019; 126:7-13. <https://doi.org/10.1016/j.envint.2019.02.023>
30. **Sun SZ**, Tian L, Cao WN, Lai PC, PY Wong, Lee RSY, Mason TG, Tang, R, Kra ̈mer A, Wong CM. [Urban climate modified short-term association of air pollution with pneumonia mortality in Hong Kong](lib/Sun-Urban%20climate%20modified%20short-term%20associat.pdf). Science of The Total Environment 2019; 646:618-624. <https://doi.org/10.1016/j.scitotenv.2018.07.311>
31. **Sun SZ**, Cao WN, Mason TG, Ran JJ, Qiu H, Li JH, Yang Y, Lin HL, Tian L. [Increased susceptibility to heat for respiratory hospitalizations in Hong Kong](lib/Sun-Increased%20susceptibility%20to%20heat%20for%20respi.pdf). Science of The Total Environment 2019; 666:197-204. <https://doi.org/10.1016/j.scitotenv.2019.02.229>
32. **Sun SZ**, Francine L, Jaime H, Qiu H, Wang Y, Wong CM, Lee RSY, Tian L. [Seasonal temperature variability and emergency hospital admissions for respiratory diseases: a population-based cohort study](lib/951.full.pdf). Thorax 2018; 73:951-958. <http://dx.doi.org/10.1136/thoraxjnl-2017-211333> (Editorial: Lam KBH. [Stable or fluctuating temperatures in winter: which is worse for your lungs?](lib/902.full.pdf) Thorax 2018; 73(10):902-903)
33. **Sun SZ**, Qiu H, Ho KF, Tian L. [Chemical components of respirable particulate matter associated with emergency hospital admissions for Type 2 diabetes in Hong Kong](lib/Sun-Chemical%20components%20of%20respirable%20particul.pdf). Environment International 2016; 97: 93-99. <https://doi.org/10.1016/j.envint.2016.10.022>
34. **Sun SZ**, Tian L, Qiu H, Chan KP, Tsang H, Tang R, Lee RSY, Thach TQ, Wong CM. [The influence of pre-existing health conditions on short-term mortality risks of temperature: Evidence from a prospective Chinese elderly cohort in Hong Kong](lib/Sun-The%20influence%20of%20pre-existing%20health%20condi.pdf). Environmental Research 2016; 148:7-14. <https://doi.org/10.1016/j.envres.2016.03.012>
35. Qiu H, **Sun SZ** (**equal contributors**), Tang R, Chan KP, Tian L. [Pneumonia hospitalization risk in the Elderly attributable to cold and hot temperature in Hong Kong](lib/Qiu-Pneumonia%20hospitalization%20risk%20in%20the%20elde.pdf). American Journal of Epidemiology 2016; 184 (8):570-578. <https://doi.org/10.1093/aje/kww041>
36. **Sun SZ**, Cao P, Chan KP, Tsang H, Wong CM, Thach TQ. [Temperature as a modifier of the effects of fine particulate matter on acute mortality in Hong Kong](lib/Sun-Temperature%20as%20a%20modifier%20of%20the%20effects%20o.pdf). Environmental Pollution 2015; 205:357-364. <https://doi.org/10.1016/j.envpol.2015.06.007>

### **Co-author**
64. Chen ZH, Tian Y, Liu J, Ran JJ, **Sun SZ**, Zhao S, Ge Y, Martinez L, Chen X, Cao PH. COVID-19 and sepsis-related excess mortality in the US during the first three years: A national-wide time series study. American Journal of Epidemiology 2024; https://doi.org/10.1093/aje/kwae411
64. Zhang YD, Gao XG, Zhu HY, Zhou Q, Cai XX, Koch PA, **Sun SZ**, Yu HL. Integrative development of a concise screening questionnaire for early detection of pregnant women at risk for dystrophy. 2024;
63. Mi J, Wang JP, Chen LP, Guo ZH, Lei H, Chong MKC, Talifu JT, Yang SM, Luotebula K, Ablikemu M, Ma C, Lu WL, Luo ZH, Liu CF, **Sun SZ**, Dai JH, Wang KL, Zhao S. [Real-world effectiveness of influenza vaccine against medical-attended influenza infection during 2023/24 season in Ili Kazakh Autonomous Prefecture, China: A test-negative, case-control study](lib/Real-world effectiveness of influenza vaccine.pdf). Human Vaccines & Immunotherapeutics 2024; 20(1):2394255. https://doi.org/10.1080/21645515.2024.2394255

60. Relationship between global warming and autism spectrum disorder from 1990 to 2019. BJPsych Open 2024.
60. Real-world evaluation of inactivated BBIBP-CorV COVID-19 vaccine safety on males fertility in Urumqi, China: A retrospective cohort study. 2024;
60. Chen ZH, Wang X, Liu ML, Wu WH, Liu H, Sun Y, Jiang M, Tang XJ, Zou X, Li L, Ran JJ, **Sun SZ**, Zhao S, Fang SS, Cao PH. Resurgence of influenza following the exit of restrict non-pharmacological interventions in Shenzhen, China: A one-year observational study. 2024;
60. Chen ZH, Tian Y, Liu J, Ran JJ, **Sun SZ**, Zhao S, Ge Y, Martinez L, Chen X, Cao PH. COVID-19 and sepsis-related excess mortality in the US during the first three years: A national-wide time series study. American Journal of Epidemiology 2024;
60. Qiu H, **Sun SZ**, Wong TW, Qiu X, Ho KF, Wong ELY. Ambient temperature-related attributable risk for emergency asthma hospitalizations and length of stay in Hong Kong. Urban Climate 2024;
59. Shen C, Tong XN, Ran JJ, **Sun SZ**, Yang Q, Shen HY, Yao XX. [Associations between residential environments and late-onset schizophrenia in UK Biobank: Interaction with genetic risk factor](lib/Associations between.pdf). Schizophrenia Research 2024;270:85-93. https://doi.org/10.1016/j.schres.2024.06.008
58. Guo ZH, Zeng T, Lu YQ, **Sun SZ**, Liang X, Ran JJ, Wu YS, Chong MK, Wang K, Zhao S. [Transmission risks of Omicron BA.5 following inactivated COVID-19 vaccines among children and adolescents in China](lib/maincm.pdf). Communications Medicine 2024; 4:92. https://doi.org/10.1038/s43856-024-00521-y
57. Thompson R, Tong XN, Shen XY, Ran JJ, **Sun SZ**, Yao XX, Shen C. Longitudinal associations between air pollution, noise and green space exposure and incident dementia as mediated by MRI-measured brain volumes in the UK Biobank. Environment International 2024. 
57. Dong YQ, Cao WN, Wei J, Chen YJ, Zhang YH, **Sun SZ**, Hu F, Cai Y. [Health effect of multiple air pollutant mixture on sarcopenia among middle-aged and older adults in China](lib/1-s2.0-S0147651324007103-main.pdf). Ecotoxicology and Environmental Safety 2024; 281:116634.
57. Ge Y, Cao WN, **Sun SZ**, Ross M, Shen Y. The seasonal influenza vaccine cannot trigger a Titer increase among some elderly individuals. 2024; e12380.
54. Yuan K, Shi WY, Lv X, Zhang YC, Liu RY, Zhang ZY, **Sun SZ**, Wu LZ, Cao WN. Exposure to hourly non-optimal ambient temperature and temperature change between neighboring days and risk of emergency department visits for cause-specific cardiovascular disease: a multicenter case-crossover study 2024.
54. Ouyang YH, Yang J, Zhang JX, Yan Y, **Sun SZ**, Wang JJ, Li XB, Chen R, Zhang L. [Airborne pollen exposure and the risk of hospital admission for allergic rhinitis in Beijing: a time-stratified case-crossover study](lib/ClinicalTranslationalAll.pdf). Clinical and Translational Allergy 2024; e12380. https://doi.org/10.1002/clt2.12380
54. Zhou SD, Su MT, Shen P, Yang ZM, Chai PF, **Sun SZ**, Lin HB, Shui LM, Zhang N, Xu M, Zheng ZJ, Wang JB, Zhang ZY, Chen K. [Association between drinking water quality and mental health and the modifying role of diet: a prospective cohort study](lib/s12916-024-03269-3.pdf). BMC Medicine 2024; 22: 53. https://doi.org/10.1186/s12916-024-03269-3
54. Shi HX, Sun MT, Shen P, Ma JX, Zhou QF, Yang ZM, Chai PF, **Sun SZ**, Lin HB, Shui LM, Liang ZS, Huang SY, Zhang N, Wang JB, Zhang ZY, Chen K. Diet modified the association of metals and nonmetals in drinking water with major adverse cardiovascular events (MACE) in a prospective cohort study. BMC Medicine 2024;

52. Chen ZH, Jia PP, Xie D, Xie JY, Liu J, Cao WN, Han LF, Ran JJ, **Sun SZ**, Zhao S, Ge Yang, Martinez L, Chen X, Cao PH. Kidney failure-related excess mortality during the first three years of the COVID-19 pandemic in the United States: A nation-wide, population-based analysis. 2024;

45. Ku PW, Steptoe A, Hamer M, Yu Bin, Hvidtfeldt UA, Lao XQ, Lin HH, Lo WC, Raaschou-Nielsen O, **Sun SZ**, Tian LW, Zeng YQ, Zhang YQ, Xia Y, Chen LJ. Are the associations of leisure-time physical activity with mortality modified by ambient PM~2.5~? A systematic review and harmonized meta-analysis involving 1.48 million participants.  2024;

51. Zeng T, Wang KL, Guo ZH, **Sun SZ**, Zhai ZY, Lu YQ, Teng ZD, He DH, Wang K, Tian MZ, Zhao S. [Distinguishing the vaccine effectiveness of inactivated BBIBP-CorV vaccine booster against the susceptibility, infectiousness, and transmission of Omicron stains: A retrospective cohort study in Urumqi, China](lib/s40121-023-00873-3.pdf). Infectious Diseases Therapy 2023; https://doi.org/10.1007/s40121-023-00873-3.
48. Li WJ, Li N, Liang ZS, Hou XD, Si Y, Wang X, Feng XP, Tai BJ, Hu DY, Lin HC, Wang B, Wang CX, Zheng SG, Liu XN, Rong WS, Wang WJ, **Sun SZ**, Meng HX, Zhang ZY. [Long-term exposure to ambient fine particulate matter and periodontitis: An observational study using nationally representative survey data](lib/17902641.pdf). Journal of Clinical Periodontology 2024; https://doi.org/10.1111/jcpe.13950

48. Li JH, Wu HS, Xing WW, Li X, Han ZS, Ji RY, Deng ZY, Jung MJ, **Sun SZ**, Chung BI, Cardenas A, Langston ME. [Air pollution mixture associated with oxidative stress exacerbation and symptoms deterioration in allergic rhinitis patients: evidence from a panel study](lib/1-s2.0-S0048969724028353-main.pdf). Science of the Total Environment 2024;930:172688. https://doi.org/10.1016/j.scitotenv.2024.172688

48. Zhao S, Guo ZH, Sun DY, Wang K, **Sun SZ**, Peng ZH, He DH, Chong MKC, Yeoh EK. modelSSE: An R package for characterizing infectious disease superspreading from contact tracing surveillance data. 2023.

48. Shi HX, Zhou Q, Zhang HJ, **Sun SZ**, Zhao JF, Wang YS, Huang J, Jin YZ，Zheng ZJ, Wu RY, Zhang ZY. [The combined effects of hourly multi-pollutant on the risk of ambulance emergency calls: A seven-year time series study](lib/toxics-11-00895.pdf). Toxics 2023; 11(11):895. https://doi.org/10.3390/toxics11110895.
47. Xu QS, Zhou QF, Chen JJ, Li T, Ma JX, Du RM, Su MT, Li J, Xu M, **Sun SZ**, Ma J, Ramanathan M. [The incidence of asthma attributable to temperature variability: an ecological study based on 1990-2019 GBD data](lib/1-s2.0-S0048969723053512-main.pdf). Science of the Total Environment 2023; 904:166726. https://doi.org/10.1016/j.scitotenv.2023.166726

45. Zhang YD, Gao XG, Zhu HY, **Sun SZ**, Contento IR, Koch PA, Yu HL. [Lipid-focused dietary education intervention in pregnant women: study protocol for an open-label, parallel, randomised, intervention study addressing adverse pregnancy outcomes in China](lib/e076911.full.pdf). BMJ Open 2024;14(1):e076911. https://doi.org/10.1136/bmjopen-2023-076911
45. Luo ZH, Zeng T, Zhao S, Liang J, **Sun SZ**, Ni YK, Yan CY, Yin Liang, Wang L, Wang K, Guo ZH. Short-term change in IgG antibody elicited by Omicron BA.5 infection and inhaled Ad5-nCoV vaccine among healthcare workers. 2024.
45. Zeng T, Lu YQ, Zhao YJ, Guo ZH, **Sun SZ**, Teng ZD, Tian MZ, Wang J, Li SL, Fan XC, Wang WM, Cai YL, Liao GZ, Liang X, He DH, Wang K, Zhao S. [Effectiveness of the booster dose of inactivated COVID-19 vaccine against Omicron BA.5 infection: A matched cohort study of adult close contacts](lib/s12931-023-02542-y.pdf). Respiratory Research 2023;24:246. https://doi.org/10.1186/s12931-023-02542-y
46. Sun YX, Guo ZH, Gu X, **Sun SZ**, Wang K, Xie SS, Zhao S. [Influenza vaccine effectiveness against influenza A during the delayed 2022/23 epidemic in Shihezi, China](lib/1-s2.0-S0264410X23009714-main.pdf). Vaccine 2023; 41:5683-5685. https://doi.org/10.1016/j.vaccine.2023.08.039
45. Lu ZH, Sun B, Wang YX, Wu YR, Chen YJ, **Sun SZ**, Liang SJ, Xu S, Chang H, Chen HG, Zhang J. [Ozone exposure associates with sperm quality indicators: Sperm telomere length as a potential mediating factor](lib/1-s2.0-S0304389423015753-main.pdf). Journal of Hazardous Materials 2023;459:132292. https://doi.org/10.1016/j.jhazmat.2023.132292
45. Guo ZH, Zhao S, **Sun SZ**, Wang Kai, Ran JJ, He DH, Wei YC, Wang HW, Sun J, Chong KC, Yeoh EK. [Estimating the serial interval of Marburg virus human-to-human transmission from a case cluster seeded by a cross-border traveler](lib/taad100.pdf). Journal of Travel Medicine 2023; 30(5):taad100. https://doi.org/10.1093/jtm/taad100

43. Zhao S, Guo ZH, **Sun SZ**, Hung CT, Leung EYM, Wei YC, Wang HW, Li KH, Yam CHK, Chow TY, Gao J, Jia KM, Chong KC, Yeoh EK. [Effectiveness of BNT162b2 and Sinovac vaccines against the transmission of SARS-CoV-2 during Omicron-predominance in Hong Kong: A retrospective cohort study of COVID-19 cases](lib/1-s2.0-S1386653223001701-main.pdf). Journal of Clinical Virology 2023; 166:105547. https://doi.org/10.1016/j.jcv.2023.105547
43. Lu YQ, Guo ZH, Zeng T, **Sun SZ**, Lu YM, Teng ZD, Tian MZ, Wang J, Li SL, Fan XC, Luan ZM, Wang WM, Cai YL, Wang K, Zhao S. [Case clustering, contact stratification, and transmission heterogeneity of SARS-CoV-2 Omicron BA.5 variants in Urumqi, China: An observational study](lib/jogh-13-06018.pdf). Journal of Global Health; 2023(13):06018. https://doi.org/10.7189/jogh.13.06018
43. Cheng J, Zheng H, Wei J, Huang CR, Ho HC, **Sun SZ**, Phung D, Wang XL, Bai ZL, Hossain MZ, Tong SL, Sun Hong, Xu ZW. [Short-term residential exposure to air pollution and risk of acute myocardial infarction deaths at home in China](lib/Short-term_residential_exposure_to_air_pollution_a.pdf). Environmental Science and Pollution Research 2023;30:76881-76890. https://doi.org/10.1007/s11356-023-27813-5
43. Zhou SD, Chai PF, Dong XJ, Liang ZS, Yang ZM, Li JX, Teng GG, **Sun SZ**, Xu M, Zheng ZJ, Wang JB, Zhang ZY, Chen K. [Drinking water quality and inflammatory bowel disease: a prospective cohort study](lib/s11356-023-27460-w.pdf). Environmental Science and Pollution Research 2023; 30:71171-71183. https://doi.org/10.1007/s11356-023-27460-w
43. Li P, Yang QQ, Wang XP, **Sun SZ**, Cao WN, Yu SW, Zhan SY, Sun F. [Dose-response relationship between physical activity and nonalcoholic fatty liver disease: A prospective cohort study](lib/Dose_response_relationship_between_physical.496.pdf). Chinese Medical Journal 2023;132(12): 1494-1496. https://doi.org/10.1097/CM9.0000000000002532
43. Zhou Q, Shi HX, Wu NY, Zhu H, Liang ZS, **Sun SZ**, Zhao JF, Wang YS, Huang J, Jin YZ, Zheng ZJ, Qin CZ, Li JY, Zhang ZY. [Associations between hourly ambient particulate matter air pollution and ambulance emergency calls among 3,022,164 patients: time stratified case-crossover study](lib/JMIRPH.pdf). JMIR Public Health and Surveillance 2023;9:e47022. https://doi.org/10.2196/47022
43. Sun YY, Wang ZH, **Sun SZ**, Cui L, Zhu XQ, Ho SY, Qi SG. Cognitive activities, lifestyle factors and risk of cognitive impairment, with an analysis of the apolipoprotein epsilon 4 genotype. Gerontology 2023; 69(9):1137-1146. https://doi.org/10.1159/000531109
45. Du RM, Jiao WT, Ma JX, Zhou QF, Liang ZS, **Sun SZ**, Ahmed OG, Rowan NR, Pinto JM, Ramanathan M, Zhang ZY. [Association between ambient temperature and chronic rhinosinusitis](lib/Int Forum Allergy Rhinol - 2023 - Du - Association between ambient temperature and chronic rhinosinusitis.pdf). International Forum of Allergy and Rhinology 2023; 13(10):1906-1914. https://doi.org/10.1002/alr.23152
43. Wang K, Guo ZH, Zeng Ting, **Sun SZ**, Lu YM, Wang J, Li SL, Fan XC, Luan ZM, Li HL, Zhang J, Wang YD, Lu YQ, Zhao S. [Transmission characteristics and inactivated vaccine effectiveness against the transmission of SARS-CoV-2 Omicron BA.5.2 variants in Urumqi, China](lib/wang_2023_oi_230194_1679406264.17489.pdf). JAMA Network Open 2023;6(3):e235755. https://doi.org/10.1001/jamanetworkopen.2023.5755
43. Yang LP, Sun HF, Bai Y, **Sun SZ**, Wu XM, Gan ZH, Du JQ, Du JF. [Trends and projections of stomach cancer incidence in Hong Kong: A population-based study](lib/Trends and Projections of Stomach Cancer Incidence in Hong Kong A Population Based Study.pdf). Cancer Investigation 2023;41(4):319-329. https://doi.org/10.1080/07357907.2022.2126982
41. Chen JJ, Jiao ZH, Liang ZS, Ma JX, Xu M, Biswal S, Ramanathan M, **Sun SZ**, Zhang ZY. [Association between temperature variability and global meningitis incidence](lib/1-s2.0-S0160412022005761-main.pdf). Environment International 2023; 171: 107649. https://doi.org/10.1016/j.envint.2022.107649
40. Guo ZH, Zhao S, **Sun SZ**, He DH, Chong KC, Yeoh EK. [Estimation of the serial interval of monkeypox during the early outbreak in 2022](lib/proof.pdf). Journal of Medical Virology 2023; 95(1):e28248. https://doi.org/10.1002/jmv.28248
40. IPOP study co-authors, [Changes in preterm birth and stillbirth during  COVID-19 lockdowns in 26 countries](lib/s41562-023-01522-y.pdf). Nature Human Behaviour 2023; 7:529-544. https://doi.org/10.1038/s41562-023-01522-y 
41. Stowell JD, Sun YT, Spangler KR, Bernstein A, Weinberger KR, **Sun SZ**, Wellenius GA. [Warm-Season temperatures and emergency department visits among children with health insurance](lib/Stowell_2023_Environ._Res.__Health_1_015002.pdf). Environmental Research: Health 2023; 1:015002. https://doi.org/10.1088/2752-5309/ac78fa
38. Adams Q, Sun YT, **Sun SZ**, Wellenius GA. [Internet searches and heat-related emergency department visits in the United States](lib/Adams_et_al-2022-Scientific_Reports.pdf).Scientific Report 2022; 12:9031. https://doi.org/10.1038/s41598-022-13168-3
39. Ge Y, Martinez L, **Sun SZ**, Chen ZP, Zhang F, Li F, Sun WW, Chen EF, Pan JR, Li CW, Sun JM, Handel A, Ling F, Shen Y. [Covid-19 transmission dynamics among close contacts of Covid-19 index cases: a population-based cohort study in Zhejiang Province, China](lib/jamainternal_ge_2021_oi_210046_1628543955.60954.pdf). JAMA Internal Medicine 2021; 181(10): 1343-1350. <https://doi.org/10.1001/jamainternmed.2021.4686>.
40. Weinberger KR, Wu X, **Sun SZ**, Spangler KR, Nori-Sarma A, Schwartz J, Requia W, Sabath BM, Braun D, Zanobetti A, Dominici F, Wellenius GA. [Heat warnings, mortality, and hospital admissions among older adults in the United States](lib/1-s2.0-S0160412021004591-main.pdf). Environment International 2021;157(2021): 106834. <https://doi.org/10.1016/j.envint.2021.106834>\
41. Deng YL, Liao JQ, Zhou B, Zhang WX, Liu C, Yuan XQ, Chen PP, Miao Y, Luo Q, Cui FP, Zhang M, **Sun SZ**, Zheng TZ, Xia W, Li YY, Xu SQ, Zeng Q. [Early life exposure to air pollution and cell-mediated immune responses in preschoolers](lib/1-s2.0-S0045653521024358-main.pdf). Chemosphere 2022; 186(2022):131963. <https://doi.org/10.1016/j.chemosphere.2021.131963>
42. Cao W, Li J, **Sun SZ**, Sturm C, Peng L, Gu J, Hao C, Hou F, Wei D, You X, Deng Y, Ekstrom AM. [HIV serostatus disclosure among men who have sex with men in China in the era of U=U and PrEP](lib/Cao_2021_AIDS%20and%20Behavior_ask%20and%20tell%20U=U.pdf). AIDS and Behavior 2022;26:1477–1488. <https://doi.org/10.1007/s10461-021-03502-7>
43. Weinberger KR, Kulik ER, Boehme AK, **Sun SZ**, Dominici F, Wellenius GA. [Association between Hurricane Sandy and emergency department visits in New York City by age and cause](lib/kwab127.pdf). American Journal of Epidemiology 2021; 190(10):2138-2147. <https://doi.org/10.1093/aje/kwab127>
44. Ran JJ, Zhang YM, Han LF, **Sun SZ**, Zhao S, Shen C, Zhang XH, Chan KP, Lee RSY, Qiu YL, Tian LW. [The joint association of physical activity and fine particulate matter exposure with incident dementia in Hong Kong older adults](lib/1-s2.0-S0160412021002701-main.pdf). Environment International 2021; 156(2021):106645. <https://doi.org/10.1016/j.envint.2021.106645>
45. Zhang M, Liu C, Cui FP, Chen PP, Deng YL, Luo Q, Miao Y, **Sun SZ**, Li YF, Lu WQ, Zeng Q. [The role of oxidative stress in association between disinfection by-products exposure and semen quality: A mediation analysis among men from an infertility clinic](lib/1-s2.0-S004565352033054X-main.pdf). Chemosphere 268 (2021):128856. <https://doi.org/10.1016/j.chemosphere.2020.128856>
46. Ran JJ, Schooling CM, Han LF, **Sun SZ**, Zhao S, Zhang XH, Chan KP, Guo F, Lee RSY, Qiu YL, Tian LW. [Long-term exposure to fine particulate matter and dementia incidence: A cohort study in Hong Kong](lib/1-s2.0-S026974912036992X-main.pdf). Environmental Pollution 2021; 271(2021):116303. <https://doi.org/10.1016/j.envpol.2020.116303>
47. Yang P, Lin BG, Zhou B, Cao WC, Chen PP, Deng YL, Hou J, **Sun SZ**, Zheng TZ, Lu WQ, Cheng LM, Zeng WJ, Zeng Q. [Sex-specific associations of prenatal exposure to bisphenol A and its alternatives with fetal growth parameters and gestational age](lib/1-s2.0-S0160412020322601-main.pdf). Environment International 2021; 146(2021):106305. <https://doi.org/10.1016/j.envint.2020.106305>.
48. Ran JJ, Kioumourtzoglou M, **Sun SZ**, Han LF, Zhao S, Zhu W, Li JH, Tian LW. [Source-specific Volatile Organic Compounds and Emergency Hospital Admissions for Cardiorespiratory Diseases](lib/ijerph-17-06210.pdf). International Journal of Environmental Research and Public Health. 2020; 17:6210. <https://doi.org/10.3390/ijerph17176210>
49. Ran JJ, **Sun SZ**, Han LF, Zhao S, Chen DY, Guo F, Li JH, Qiu H, Lei YJ, Tian LW. [Fine particulate matter and cause-specific mortality in the Hong Kong elderly patients with chronic kidney disease](lib/Ran-2020.pdf). Chemosphere 2020; 247:125913. <https://doi.org/10.1016/j.chemosphere.2020.125913>
50. Ran JJ, Yang AM, **Sun SZ**, Han LF, Qiu H, Mason TG, Li JH, Yang Y, Chan KP, Tian L. [Long-term exposure to ambient fine particulate matter and mortality of renal failure: A retrospective cohort study in Hong Kong](lib/Ran-AJE.pdf). American Journal of Epidemiology 2020; 189 (6):602-612. <https://doi.org/10.1093/aje/kwz282>
51. Chen D, Mayvaneh F, Baaghideh M, Entezari A, Ho HC, Xiang Q, Jiao A, Zhang F, Hu K, Chen G, Zhao Q, **Sun SZ**, Ma L, Zhang Y. [Utilizing daily excess concentration hours to estimate cardiovascular mortality and years of life lost attributable to fine particulate matter in Tehran, Iran](lib/Chen-2019.pdf). Science of the Total Environment 2020; 703:134909. <https://doi.org/10.1016/j.scitotenv.2019.134909>
52. Zhang YQ, Xiang QQ, Yu CH, Bao JZ, Ho HC, **Sun SZ**, Ding Z, Hu KJ, Zhang L. [Mortality risk and burden associated with temperature variability in China, United Kingdom and United States: Comparative analysis of daily and hourly exposure metrics](lib/zhang2019.pdf). Environmental Research 2019; 179:108771. <https://doi.org/10.1016/j.envres.2019.108771>
53. Cao WN, Wong HG, Mo PKH, **Sun SZ**, Hu YHJ. [Mental health problems of female spouses of men living with HIV in Sichuan, China: A qualitative study](lib/Cao-2019.pdf) Journal of the Association of Nurses in AIDS Care 2020; 31(5):526-534. <https://doi.org/10.1097/JNC.0000000000000104>
54. Lin HL, Guo YF, Ruan ZL, Yang Y, Chen YB, Zheng Y, Cummings-Vaughn LA, Rigdon SE, Vaughn MG, **Sun SZ**, Zhang LL, Wang XJ, Qian ZM, Wu F. [Ambient PM~2.5~ and O~3~ and their combined effects on prevalence of presbyopia among the elderly: A cross-sectional study in six low- and middle-income countries](lib/Lin-Ambient%20PM2.%205%20and%20O3%20and%20their%20combined%20e.pdf). Science of The Total Environment 2019; 655:168-173. <https://doi.org/10.1016/j.scitotenv.2018.11.239>
55. Tonya GM, Chan KP, Schooling MC, **Sun SZ**, Yang AM, Yang Y, Benjamin B, Tian L. [Air quality changes after Hong Kong shipping emission policy: An accountability study](lib/Mason-Air%20quality%20changes%20after%20Hong%20Kong%20ship.pdf). Chemosphere 2019; 226:616-624. <https://doi.org/10.1016/j.chemosphere.2019.03.173>
56. Ran JJ, **Sun SZ**, Yang AM, Yang L, Han LF, Mason TG, Chan KP, Li JH, Tian LW. [Effects of ambient benzene and toluene on emergency COPD hospitalizations: a time series study in Hong Kong](lib/Ran-Effects%20of%20ambient%20benzene%20and%20toluene%20on.pdf). Science of The Total Environment 2018; 657:28-35. <https://doi.org/10.1016/j.scitotenv.2018.12.015>
57. Dai YR, Qiu H, **Sun SZ**, Yang Y, Lin HL, Tian L. [Age-dependent effect of ambient ozone on emergency asthma hospitalizations in Hong Kong](lib/Dai-Age-dependent%20effect%20of%20ambient%20ozone%20on%20e.pdf). The Journal of Allergy and Clinical Immunology 2018; 141(4):1532-1534. <https://doi.org/10.1016/j.jaci.2018.01.006>
58. Qiu H, Schooling CM, **Sun SZ**, Tsang H, Tang R, Yang Y, Wong CM, Lee RSY, Tian L. [Long-term exposure to fine particulate matter air pollution and Type 2 diabetes mellitus in elderly: a cohort study in Hong Kong](lib/Qiu-Long-term%20exposure%20to%20fine%20particulate%20mat.pdf). Environment International 2018; 113: 350-356. <https://doi.org/10.1016/j.envint.2018.01.008>
59. Yang Y, Pun V, **Sun SZ**, Lin HL, Mason TG, Qiu H. [Particulate matter components and Health: a literature review on exposure assessment](lib/Yang-Particulate%20matter%20components%20and%20health_.pdf). Journal of Public Health and Emergency 2018:2:14.10.21037/jphe.2018.03.03
60. Ran JJ, Qiu H, **Sun SZ**, Tian L. [Short-term effects of ambient TEX (toluene, ethylbenzene, and xylene combined) on cardiorespiratory mortality in Hong Kong](lib/Ran-Short-term%20effects%20of%20ambient%20benzene%20and.pdf). Environment International 2018; 117: 91-98. <https://doi.org/10.1016/j.envint.2018.04.049>
61. Ran JJ, Qiu H, **Sun SZ**, Yang AM, Tian L. [Are ambient volatile organic compounds environmental stressors for heart failure?](lib/1-s2.0-S0269749118311564-main.pdf) Environmental Pollution 2018;242: 1810-1816. <https://doi.org/10.1016/j.envpol.2018.07.086>
62. Qiu H, **Sun SZ**, Tsang, H, Wong CM, Lee RSY, Schooling CM, Tian L. [Fine particulate matter exposure and incidence of stroke: A cohort study in Hong Kong](lib/00006114-201705020-00007.pdf). Neurology 2017;88: 1-9. <https://doi.org/10.1212/WNL.0000000000003903>
63. Tian L, Qiu H, **Sun SZ**, Tsang H, Chan KP, Leung WK. [Association between Emergency admission for peptic ulcer bleeding and air pollution: A case-crossover analysis in Hong Kong Elderly population](lib/Tian-Association%20between%20emergency%20admission%20f.pdf). The Lancet Planetary Health 2017;1:e74-81. [https://doi.org/10.1016/S2542-5196(17)30021-9](https://doi.org/10.1016/S2542-5196(17)30021-9){.uri}
64. Tian L, **Sun SZ**. [Comparison of health impact of air pollution between China and other countries](lib/Tian-Comparison%20of%20Health%20Impact%20of%20Air%20Pollut.pdf). Advances in Experimental Medicine and Biology 2017; 1017:215-232. <https://doi.org/10.1007/978-981-10-5657-4_9>
65. Li J, **Sun SZ**, Tang R, Qiu H, Huang Q, Mason GM, Tian L. [Major air pollutants and COPD: A Systematic review and Meta-analysis](lib/Li-Major%20air%20pollutants%20and%20risk%20of%20COPD%20exace.pdf). International Journal of Chronic Obstructive Pulmonary Disease 2016; 11(1):3079-3091. <https://doi.org/10.2147/COPD.S122282>
66. Tian L, Qiu H, **Sun SZ**, Lin H. [Emergency cardiovascular hospitalizations risk attributable to cold temperatures in Hong Kong](lib/Tian-Emergency%20Cardiovascular%20Hospitalizations.pdf). Circulation: Cardiovascular Quality and Outcomes 2016; 9(2):135-142. <https://doi.org/10.1161/CIRCOUTCOMES.115.002410> \n

For citation records, please refer to [my Google Scholar page](https://scholar.google.com.hk/citations?hl=en&user=R0S2h00AAAAJ&view_op=list_works&sortby=pubdate).
